# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlas < Formula
  desc "Self-hosted LLM inference platform — Anthropic & OpenAI compatible APIs on your own hardware"
  homepage "https://github.com/orchestra-hq/atlas"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orchestra-hq/atlas/releases/download/v0.1.0/atlas_0.1.0_darwin_amd64.tar.gz"
      sha256 "7dd7e425a7f4a8779cecd60c8a6f21d345ab4b5811d7997df59eb0ea6fe82b4c"

      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orchestra-hq/atlas/releases/download/v0.1.0/atlas_0.1.0_darwin_arm64.tar.gz"
      sha256 "2bb1e2a66f7c2133ba93cf633f0ef503b9e92fefc5efe45e7a925c60b114756e"

      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchestra-hq/atlas/releases/download/v0.1.0/atlas_0.1.0_linux_amd64.tar.gz"
      sha256 "a09f603075cee7dcdf4302532e84c8cd4f3dc1433effd2eaf7f9cf4176d945bc"
      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchestra-hq/atlas/releases/download/v0.1.0/atlas_0.1.0_linux_arm64.tar.gz"
      sha256 "552f7d0ce7e305e3003da0b5eb09d4294c2c249f9aa3e0ca6797fbe370736bd7"
      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  test do
    system "#{bin}/atlas", "--version"
  end
end
