# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlas < Formula
  desc "Self-hosted LLM inference platform — Anthropic & OpenAI compatible APIs on your own hardware"
  homepage "https://github.com/orchestra-hq/atlas"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orchestra-hq/atlas/releases/download/v0.1.0/atlas_0.1.0_darwin_amd64.tar.gz"
      sha256 "3b6e4c070114e3a31b29ad4c7a13f004d5403a3553e98e66098b517871556a42"

      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orchestra-hq/atlas/releases/download/v0.1.0/atlas_0.1.0_darwin_arm64.tar.gz"
      sha256 "4fb91964b1cf4927724bd228b7058cdd408c678405370c162fc8a01d55febbf6"

      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchestra-hq/atlas/releases/download/v0.1.0/atlas_0.1.0_linux_amd64.tar.gz"
      sha256 "af2505354f649c37d738c96ed1618979eb300ebd7c9a041f2ef2582b70a1a96a"
      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchestra-hq/atlas/releases/download/v0.1.0/atlas_0.1.0_linux_arm64.tar.gz"
      sha256 "a0fec485c813195e6225e62018f2e28c92b4dd9a0d5aa66312e2dc81354fe824"
      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  test do
    system "#{bin}/atlas", "--version"
  end
end
